TS_SEARCH_PATHS=(~/worktrees/dd-go ~/worktrees/dd-source ~/worktrees/dogweb ~/go/src/github.com/DataDog ~/worktrees/logs-backend ~/worktrees/k8s-resources ~/neovim_dev_plugins ~/ ~/dd ~/workspaces/* ~/worktrees/*)
TS_SESSION_COMMANDS=(nvim)

